const bcrypt = require('bcryptjs');

const categories = [
  {
    name: 'Grocery & Staples',
    slug: 'grocery-staples',
    icon: '🌾',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    description: 'Rice, wheat, atta, dals, spices, edible oils and daily cooking essentials.',
    subCategories: ['Rice', 'Wheat & Atta', 'Dal & Pulses', 'Oil & Ghee', 'Spices', 'Sugar & Salt'],
    itemCount: 28
  },
  {
    name: 'Fresh Produce',
    slug: 'fresh-produce',
    icon: '🥦',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=600&q=80',
    description: 'Farm-fresh vegetables, organic fruits, greens and seasonal harvests.',
    subCategories: ['Vegetables', 'Fruits', 'Herbs & Seasoning'],
    itemCount: 20
  },
  {
    name: 'Dairy & Eggs',
    slug: 'dairy-eggs',
    icon: '🥛',
    image: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?auto=format&fit=crop&w=600&q=80',
    description: 'Pure cow milk, toned milk, dahi, fresh paneer, butter, cheese and farm eggs.',
    subCategories: ['Milk', 'Curd & Paneer', 'Butter & Cheese', 'Eggs'],
    itemCount: 16
  },
  {
    name: 'Snacks & Beverages',
    slug: 'snacks-beverages',
    icon: '☕',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
    description: 'Tea, coffee, fruit juices, cold drinks, namkeen, biscuits and chocolates.',
    subCategories: ['Biscuits', 'Chips & Namkeen', 'Chocolates', 'Soft Drinks', 'Juice', 'Tea & Coffee'],
    itemCount: 24
  },
  {
    name: 'Household & Cleaning',
    slug: 'household-cleaning',
    icon: '🧼',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
    description: 'Detergents, floor cleaners, dishwashers, garbage bags and home care.',
    subCategories: ['Detergents', 'Cleaning Products', 'Kitchen Essentials', 'Paper Products'],
    itemCount: 18
  },
  {
    name: 'Personal Care',
    slug: 'personal-care',
    icon: '🧴',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    description: 'Soaps, shampoos, hair oils, body lotions, toothpastes and skincare.',
    subCategories: ['Soaps & Body Wash', 'Hair Care', 'Oral Care', 'Skin Care'],
    itemCount: 15
  },
  {
    name: 'Baby Care',
    slug: 'baby-care',
    icon: '🍼',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=600&q=80',
    description: 'Diapers, gentle wipes, baby wash, lotion, infant foods and feeding.',
    subCategories: ['Diapers & Wipes', 'Baby Food', 'Baby Hygiene'],
    itemCount: 10
  },
  {
    name: 'Stationery & Essentials',
    slug: 'stationery-essentials',
    icon: '✏️',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    description: 'Notebooks, pens, batteries, adhesives, emergency candles and repellents.',
    subCategories: ['Notebooks & Pens', 'Adhesives', 'Batteries & Home Utilities'],
    itemCount: 8
  }
];

const stores = [
  {
    storeId: 'store-baner-1',
    name: 'MART WITH US — Baner Hub',
    area: 'Baner',
    city: 'Pune',
    address: 'Shop 101-105, Primrose Mall, Baner High Street, Pune, MH 411045',
    pincode: '411045',
    contactPhone: '+91 98230 45678',
    isOpen: true,
    rating: 4.8,
    distanceKm: 2.1,
    deliveryTimeEstimate: '20-30 min',
    coordinates: { lat: 18.5590, lng: 73.7868 }
  },
  {
    storeId: 'store-wakad-2',
    name: 'MART WITH US — Wakad Express',
    area: 'Wakad',
    city: 'Pune',
    address: 'Near Datta Mandir Chowk, Kaspate Vasti, Wakad, Pune, MH 411057',
    pincode: '411057',
    contactPhone: '+91 98230 45679',
    isOpen: true,
    rating: 4.7,
    distanceKm: 3.8,
    deliveryTimeEstimate: '25-35 min',
    coordinates: { lat: 18.5987, lng: 73.7634 }
  },
  {
    storeId: 'store-kothrud-3',
    name: 'MART WITH US — Kothrud Supercenter',
    area: 'Kothrud',
    city: 'Pune',
    address: 'Paud Road, Ideal Colony, Kothrud, Pune, MH 411038',
    pincode: '411038',
    contactPhone: '+91 98230 45680',
    isOpen: true,
    rating: 4.9,
    distanceKm: 4.5,
    deliveryTimeEstimate: '30-40 min',
    coordinates: { lat: 18.5074, lng: 73.8077 }
  }
];

// Helper to generate 105 realistic products
const products = [
  // 1. Grocery & Staples - Rice & Atta
  {
    name: 'Aashirvaad Superior MP Sharbati Atta',
    brand: 'Aashirvaad',
    category: 'Grocery & Staples',
    subCategory: 'Wheat & Atta',
    description: 'Made from the king of wheat - 100% pure Sharbati grains sourced directly from Madhya Pradesh. Delivers extra soft, fluffy rotis with rich golden aroma.',
    quantity: '5 KG',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=500&q=80'],
    mrp: 320,
    price: 285,
    discount: 11,
    stock: 75,
    rating: 4.8,
    reviewsCount: 142,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Fortune Chakki Fresh Atta',
    brand: 'Fortune',
    category: 'Grocery & Staples',
    subCategory: 'Wheat & Atta',
    description: '100% whole wheat flour, naturally rich in dietary fibre with zero added maida. Guarantees soft rotis for up to 6 hours.',
    quantity: '10 KG',
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=500&q=80'],
    mrp: 460,
    price: 419,
    discount: 9,
    stock: 50,
    rating: 4.6,
    reviewsCount: 88,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'India Gate Basmati Rice Feast Rozana',
    brand: 'India Gate',
    category: 'Grocery & Staples',
    subCategory: 'Rice',
    description: 'Aged basmati rice grains with distinct slender texture and sweet aroma. Perfect for everyday pulav, steamed rice and fried rice.',
    quantity: '5 KG',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80'],
    mrp: 495,
    price: 399,
    discount: 19,
    stock: 60,
    rating: 4.7,
    reviewsCount: 110,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Daawat Super Basmati Rice',
    brand: 'Daawat',
    category: 'Grocery & Staples',
    subCategory: 'Rice',
    description: 'Premium long grain basmati rice, naturally aged for 2 years. Fluffs up to twice its length when cooked.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=500&q=80'],
    mrp: 185,
    price: 145,
    discount: 22,
    stock: 90,
    rating: 4.6,
    reviewsCount: 76,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Royal Bullet Kolam Rice (Wada Kolam)',
    brand: 'Royal',
    category: 'Grocery & Staples',
    subCategory: 'Rice',
    description: 'Popular everyday non-sticky white rice with smooth texture. Highly preferred in Maharashtra and Gujarat homes.',
    quantity: '5 KG',
    images: ['https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=500&q=80'],
    mrp: 360,
    price: 310,
    discount: 14,
    stock: 40,
    rating: 4.5,
    reviewsCount: 45,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  // Dal & Pulses
  {
    name: 'Tata Sampann Unpolished Toor Dal',
    brand: 'Tata Sampann',
    category: 'Grocery & Staples',
    subCategory: 'Dal & Pulses',
    description: 'Unpolished arhar dal with zero water, oil or stone polishing. Retains wholesome natural nutrients and high plant protein.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80'],
    mrp: 195,
    price: 168,
    discount: 14,
    stock: 85,
    rating: 4.8,
    reviewsCount: 95,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Tata Sampann Moong Dal Dhuli',
    brand: 'Tata Sampann',
    category: 'Grocery & Staples',
    subCategory: 'Dal & Pulses',
    description: 'Yellow split moong dal, easy on digestion and quick to cook. High in protein, perfect for khichdi and halwa.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=500&q=80'],
    mrp: 175,
    price: 149,
    discount: 15,
    stock: 55,
    rating: 4.6,
    reviewsCount: 42,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Fortune Unpolished Chana Dal',
    brand: 'Fortune',
    category: 'Grocery & Staples',
    subCategory: 'Dal & Pulses',
    description: 'Organically cleaned Bengal gram split lentils. Essential for curries, dal tadka, vadas and besan batter.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=500&q=80'],
    mrp: 120,
    price: 99,
    discount: 18,
    stock: 65,
    rating: 4.5,
    reviewsCount: 38,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Nature Fresh Kabuli Chana (Chickpeas)',
    brand: 'Nature Fresh',
    category: 'Grocery & Staples',
    subCategory: 'Dal & Pulses',
    description: 'Bold-sized grade A white chickpeas. Boils to melt-in-mouth softness for Amritsari chole and hummus.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=500&q=80'],
    mrp: 180,
    price: 148,
    discount: 18,
    stock: 45,
    rating: 4.7,
    reviewsCount: 52,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Organic Rajma Chitra (Kidney Beans)',
    brand: 'Organic Tattva',
    category: 'Grocery & Staples',
    subCategory: 'Dal & Pulses',
    description: 'Himalayan speckled kidney beans with creamy texture and rich earthy taste. Ideal for Punjab-style rajma chawal.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80'],
    mrp: 210,
    price: 179,
    discount: 15,
    stock: 50,
    rating: 4.6,
    reviewsCount: 64,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  // Oil & Ghee
  {
    name: 'Fortune Sunlite Refined Sunflower Oil',
    brand: 'Fortune',
    category: 'Grocery & Staples',
    subCategory: 'Oil & Ghee',
    description: 'Enriched with Vitamins A and D. Light and clear cooking oil that preserves natural flavor of food without heaviness.',
    quantity: '1 L Pouch',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80'],
    mrp: 165,
    price: 139,
    discount: 16,
    stock: 120,
    rating: 4.8,
    reviewsCount: 168,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Amul Pure Cow Desi Ghee',
    brand: 'Amul',
    category: 'Grocery & Staples',
    subCategory: 'Oil & Ghee',
    description: 'Made from fresh cow milk cream with authentic granular (danedar) texture and golden color. Enhances rotis, dal tadka and sweets.',
    quantity: '1 L Tin',
    images: ['https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80'],
    mrp: 670,
    price: 599,
    discount: 11,
    stock: 80,
    rating: 4.9,
    reviewsCount: 220,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Saffola Gold Pro Healthy Heart Edible Oil',
    brand: 'Saffola',
    category: 'Grocery & Staples',
    subCategory: 'Oil & Ghee',
    description: 'Blended oil with Oryzanol and Dual Seed Technology (Rice Bran + Sunflower) for cholesterol management and good health.',
    quantity: '1 L Bottle',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80'],
    mrp: 200,
    price: 172,
    discount: 14,
    stock: 60,
    rating: 4.7,
    reviewsCount: 92,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Dhara Kachi Ghani Mustard Oil',
    brand: 'Dhara',
    category: 'Grocery & Staples',
    subCategory: 'Oil & Ghee',
    description: 'Traditional cold-pressed mustard oil with pungent kick and distinct aroma. Great for pickles, fish curries and stir fries.',
    quantity: '1 L Bottle',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80'],
    mrp: 175,
    price: 149,
    discount: 15,
    stock: 70,
    rating: 4.6,
    reviewsCount: 55,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  // Spices, Sugar, Salt
  {
    name: 'Tata Salt Vacuum Evaporated Iodised Salt',
    brand: 'Tata Salt',
    category: 'Grocery & Staples',
    subCategory: 'Sugar & Salt',
    description: 'Desh Ka Namak. Pure vacuum evaporated iodised salt guarantees exact iodine level crucial for mental and physical development.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=500&q=80'],
    mrp: 28,
    price: 26,
    discount: 7,
    stock: 200,
    rating: 4.9,
    reviewsCount: 310,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Madhur Pure & Hygienic Sulphur Free Sugar',
    brand: 'Madhur',
    category: 'Grocery & Staples',
    subCategory: 'Sugar & Salt',
    description: 'Refined without harmful sulphur using untouched hygienic processes. Sparkling white crystals with uniform size.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&w=500&q=80'],
    mrp: 58,
    price: 49,
    discount: 16,
    stock: 140,
    rating: 4.8,
    reviewsCount: 135,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Everest Shahi Garam Masala',
    brand: 'Everest',
    category: 'Grocery & Staples',
    subCategory: 'Spices',
    description: 'Finely blended spice mix with black pepper, cardamom, cinnamon and cloves. Adds royal aroma to veg and non-veg curries.',
    quantity: '100 g',
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80'],
    mrp: 92,
    price: 82,
    discount: 11,
    stock: 95,
    rating: 4.7,
    reviewsCount: 84,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'MDH Deggi Mirch Red Pepper Powder',
    brand: 'MDH',
    category: 'Grocery & Staples',
    subCategory: 'Spices',
    description: 'Unique blend of selected Indian red chillies that gives mild heat with intense natural crimson red color to gravies.',
    quantity: '100 g',
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80'],
    mrp: 85,
    price: 76,
    discount: 11,
    stock: 80,
    rating: 4.8,
    reviewsCount: 90,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Catch Turmeric Powder (Haldi)',
    brand: 'Catch',
    category: 'Grocery & Staples',
    subCategory: 'Spices',
    description: 'Low-temperature ground Salem turmeric with high natural curcumin content. Strong antibacterial essence and vibrant hue.',
    quantity: '200 g',
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=500&q=80'],
    mrp: 68,
    price: 58,
    discount: 15,
    stock: 110,
    rating: 4.7,
    reviewsCount: 72,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Everest Coriander Powder (Dhaniya)',
    brand: 'Everest',
    category: 'Grocery & Staples',
    subCategory: 'Spices',
    description: 'Ground from roasted fragrant coriander seeds. Thickens gravies and infuses subtle herbal notes.',
    quantity: '200 g',
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80'],
    mrp: 64,
    price: 54,
    discount: 16,
    stock: 90,
    rating: 4.6,
    reviewsCount: 60,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },

  // 2. Fresh Produce - Vegetables & Fruits
  {
    name: 'Farm Fresh Red Onions (Kanda / Pyaaz)',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    description: 'Directly sourced from Nashik farms. Crisp, pungent and firm red onions, hand-sorted for daily home cooking.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=500&q=80'],
    mrp: 45,
    price: 34,
    discount: 24,
    stock: 150,
    rating: 4.6,
    reviewsCount: 180,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Fresh Hybrid Round Tomatoes',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    description: 'Juicy, plump and glossy red tomatoes picked ripe. Perfect balance of sweetness and acidity for rasam, curries and salads.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=500&q=80'],
    mrp: 40,
    price: 28,
    discount: 30,
    stock: 130,
    rating: 4.7,
    reviewsCount: 165,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Fresh Potatoes (Aloo / Batata)',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    description: 'High-grade firm table potatoes with thin skin. Free from green patches and sprouting, perfect for boiling, frying or roasting.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=500&q=80'],
    mrp: 38,
    price: 29,
    discount: 24,
    stock: 160,
    rating: 4.6,
    reviewsCount: 140,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Fresh Green Chillies (Hari Mirch)',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    description: 'Spicy, crisp and fresh green chillies. Adds an energetic punch to chutneys and tadkas.',
    quantity: '200 g',
    images: ['https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=500&q=80'],
    mrp: 25,
    price: 18,
    discount: 28,
    stock: 90,
    rating: 4.5,
    reviewsCount: 88,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Fresh Coriander Bunch (Kothimbir)',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Herbs & Seasoning',
    description: 'Aromatic green coriander with roots washed. Freshly harvested every morning from local farmers.',
    quantity: '1 Bunch (~150 g)',
    images: ['https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=500&q=80'],
    mrp: 20,
    price: 14,
    discount: 30,
    stock: 120,
    rating: 4.8,
    reviewsCount: 110,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Fresh Garlic (Lehsun)',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    description: 'Tight-cloved dry white garlic with intense aroma. Peels easily and gives strong pungency.',
    quantity: '250 g',
    images: ['https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?auto=format&fit=crop&w=500&q=80'],
    mrp: 75,
    price: 59,
    discount: 21,
    stock: 75,
    rating: 4.6,
    reviewsCount: 65,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Fresh Ginger (Adrak)',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    description: 'Fibrous, spicy and washed ginger roots. Ideal for morning chai, gravies and immunity concoctions.',
    quantity: '250 g',
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=500&q=80'],
    mrp: 45,
    price: 35,
    discount: 22,
    stock: 80,
    rating: 4.7,
    reviewsCount: 78,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Shimla Royal Delicious Apples',
    brand: 'Orchard Fresh',
    category: 'Fresh Produce',
    subCategory: 'Fruits',
    description: 'Sweet, crisp and juicy apples hand-picked in Himachal Pradesh orchards. High in natural dietary fibre and vitamins.',
    quantity: '4 Pcs (Approx 600-700 g)',
    images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=500&q=80'],
    mrp: 180,
    price: 139,
    discount: 23,
    stock: 65,
    rating: 4.7,
    reviewsCount: 94,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Robusta Golden Bananas (Kela)',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Fruits',
    description: 'Naturally ripened sweet bananas from Jalgaon plantations. Rich in potassium, ideal for breakfast or post-workout energy.',
    quantity: '6 Pcs (~750 g)',
    images: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=500&q=80'],
    mrp: 45,
    price: 32,
    discount: 29,
    stock: 140,
    rating: 4.8,
    reviewsCount: 210,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Nagpur Sweet Oranges (Santra)',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Fruits',
    description: 'Juicy, fragrant and rich in Vitamin C. Refreshing citrus fruit directly sourced from Vidarbha orchards.',
    quantity: '1 KG (5-6 Pcs)',
    images: ['https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=500&q=80'],
    mrp: 110,
    price: 85,
    discount: 23,
    stock: 55,
    rating: 4.5,
    reviewsCount: 45,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Ruby Red Pomegranate (Anar)',
    brand: 'Farm Fresh',
    category: 'Fresh Produce',
    subCategory: 'Fruits',
    description: 'Plump red seeds with sweet-tart juice packed with antioxidants and iron.',
    quantity: '3 Pcs (~700 g)',
    images: ['https://images.unsplash.com/photo-1541344999736-83eca872f242?auto=format&fit=crop&w=500&q=80'],
    mrp: 160,
    price: 129,
    discount: 19,
    stock: 50,
    rating: 4.7,
    reviewsCount: 68,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },

  // 3. Dairy & Eggs
  {
    name: 'Amul Taaza Homogenised Toned Milk',
    brand: 'Amul',
    category: 'Dairy & Eggs',
    subCategory: 'Milk',
    description: 'Pasteurized toned milk with 3.0% fat and 8.5% SNF. Excellent for direct drinking, tea, coffee and making curd.',
    quantity: '500 ml Pouch',
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=500&q=80'],
    mrp: 27,
    price: 27,
    discount: 0,
    stock: 250,
    rating: 4.9,
    reviewsCount: 410,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-20 mins'
  },
  {
    name: 'Amul Gold Full Cream Milk',
    brand: 'Amul',
    category: 'Dairy & Eggs',
    subCategory: 'Milk',
    description: 'Wholesome full cream milk with 6.0% fat and 9.0% SNF. Rich in taste, gives thick malai and delectable kheer.',
    quantity: '500 ml Pouch',
    images: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=500&q=80'],
    mrp: 33,
    price: 33,
    discount: 0,
    stock: 200,
    rating: 4.9,
    reviewsCount: 380,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-20 mins'
  },
  {
    name: 'Amul Salted Butter Block',
    brand: 'Amul',
    category: 'Dairy & Eggs',
    subCategory: 'Butter & Cheese',
    description: 'Utterly Butterly Delicious. Pure cream butter made from fresh cows milk with a pinch of salt. Great on toast, pav bhaji and parathas.',
    quantity: '100 g',
    images: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=500&q=80'],
    mrp: 58,
    price: 55,
    discount: 5,
    stock: 150,
    rating: 4.9,
    reviewsCount: 290,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-20 mins'
  },
  {
    name: 'Milky Mist Fresh Paneer Block',
    brand: 'Milky Mist',
    category: 'Dairy & Eggs',
    subCategory: 'Curd & Paneer',
    description: 'Ultra-soft, vacuum-packed malai paneer. High in calcium and protein, stays tender in curries without turning rubbery.',
    quantity: '200 g',
    images: ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80'],
    mrp: 95,
    price: 84,
    discount: 12,
    stock: 90,
    rating: 4.7,
    reviewsCount: 145,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '15-20 mins'
  },
  {
    name: 'Amul Masti Dahi Pouch',
    brand: 'Amul',
    category: 'Dairy & Eggs',
    subCategory: 'Curd & Paneer',
    description: 'Creamy, thick and set curd prepared from pasteurized milk. Excellent probiotic accompaniment with meals.',
    quantity: '400 g',
    images: ['https://images.unsplash.com/photo-1571212515416-fef01fc43637?auto=format&fit=crop&w=500&q=80'],
    mrp: 35,
    price: 33,
    discount: 6,
    stock: 120,
    rating: 4.8,
    reviewsCount: 160,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-20 mins'
  },
  {
    name: 'Britannia Processed Cheese Slices',
    brand: 'Britannia',
    category: 'Dairy & Eggs',
    subCategory: 'Butter & Cheese',
    description: 'Individually wrapped creamy cheese slices. Melts smoothly in sandwiches, burgers and rolls.',
    quantity: '10 Slices (200 g)',
    images: ['https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=500&q=80'],
    mrp: 155,
    price: 135,
    discount: 13,
    stock: 75,
    rating: 4.7,
    reviewsCount: 92,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-20 mins'
  },
  {
    name: 'Eggoz Farm Fresh White Eggs',
    brand: 'Eggoz',
    category: 'Dairy & Eggs',
    subCategory: 'Eggs',
    description: 'UV-sanitized, antibiotic-free farm fresh eggs. Packed with 6g high quality protein per egg.',
    quantity: 'Pack of 6',
    images: ['https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=500&q=80'],
    mrp: 65,
    price: 52,
    discount: 20,
    stock: 110,
    rating: 4.8,
    reviewsCount: 154,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '15-20 mins'
  },
  {
    name: 'Farm Fresh Brown Eggs with Omega 3',
    brand: 'NutriEgg',
    category: 'Dairy & Eggs',
    subCategory: 'Eggs',
    description: 'Natural brown eggs from cage-free hens fed herbal, vegetarian diet. Naturally fortified with Omega 3 fatty acids.',
    quantity: 'Pack of 6',
    images: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=500&q=80'],
    mrp: 85,
    price: 72,
    discount: 15,
    stock: 80,
    rating: 4.7,
    reviewsCount: 88,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-20 mins'
  },

  // 4. Snacks & Beverages
  {
    name: 'Parle-G Gold Glucose Biscuits',
    brand: 'Parle',
    category: 'Snacks & Beverages',
    subCategory: 'Biscuits',
    description: 'India\'s beloved tea companion. Enriched with milk and wheat goodness, offering instant crunch and energy.',
    quantity: '1 KG Mega Pack',
    images: ['https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=500&q=80'],
    mrp: 140,
    price: 119,
    discount: 15,
    stock: 100,
    rating: 4.9,
    reviewsCount: 310,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Britannia Good Day Butter Cookies',
    brand: 'Britannia',
    category: 'Snacks & Beverages',
    subCategory: 'Biscuits',
    description: 'Crispy butter cookies with smile design. Rich melt-in-mouth creamy taste that brightens every mood.',
    quantity: '600 g (Multipack)',
    images: ['https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=500&q=80'],
    mrp: 130,
    price: 105,
    discount: 19,
    stock: 85,
    rating: 4.7,
    reviewsCount: 145,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Sunfeast Dark Fantasy Choco Fills',
    brand: 'Sunfeast',
    category: 'Snacks & Beverages',
    subCategory: 'Biscuits',
    description: 'Crisp dark chocolate cookie on the outside, overflowing with molten liquid chocolate cream within.',
    quantity: '300 g',
    images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=500&q=80'],
    mrp: 160,
    price: 129,
    discount: 19,
    stock: 70,
    rating: 4.8,
    reviewsCount: 175,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Lay\'s India\'s Magic Masala Potato Chips',
    brand: 'Lay\'s',
    category: 'Snacks & Beverages',
    subCategory: 'Chips & Namkeen',
    description: 'Crispy ridge-cut potato chips coated in an explosion of authentic Indian spices, onion and tomato zing.',
    quantity: '115 g Party Pack',
    images: ['https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=500&q=80'],
    mrp: 50,
    price: 42,
    discount: 16,
    stock: 150,
    rating: 4.8,
    reviewsCount: 260,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Kurkure Masala Munch Crunchy Snack',
    brand: 'Kurkure',
    category: 'Snacks & Beverages',
    subCategory: 'Chips & Namkeen',
    description: 'Tedha par mera crunchy corn puff snack with chatpata Indian seasoning. Irresistible snacking choice.',
    quantity: '140 g',
    images: ['https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=500&q=80'],
    mrp: 40,
    price: 34,
    discount: 15,
    stock: 130,
    rating: 4.7,
    reviewsCount: 190,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Haldiram\'s Nagpur Aloo Bhujia',
    brand: 'Haldiram\'s',
    category: 'Snacks & Beverages',
    subCategory: 'Chips & Namkeen',
    description: 'Crispy spicy strands made from potatoes, chickpea flour and refreshing mint and spices. Classic evening snack.',
    quantity: '400 g',
    images: ['https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=500&q=80'],
    mrp: 125,
    price: 104,
    discount: 17,
    stock: 90,
    rating: 4.8,
    reviewsCount: 140,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Cadbury Dairy Milk Silk Chocolate Bar',
    brand: 'Cadbury',
    category: 'Snacks & Beverages',
    subCategory: 'Chocolates',
    description: 'Silky, velvety smooth milk chocolate that melts effortlessly on the tongue. Pure indulgence in every bite.',
    quantity: '150 g',
    images: ['https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=500&q=80'],
    mrp: 195,
    price: 165,
    discount: 15,
    stock: 95,
    rating: 4.9,
    reviewsCount: 280,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Tata Tea Gold Leaf & Dust Blend',
    brand: 'Tata Tea',
    category: 'Snacks & Beverages',
    subCategory: 'Tea & Coffee',
    description: 'Exquisite blend of fine Assam CTC teas with gently pressed fragrant long leaves for unmatched kadak swad.',
    quantity: '500 g',
    images: ['https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80'],
    mrp: 340,
    price: 289,
    discount: 15,
    stock: 95,
    rating: 4.8,
    reviewsCount: 170,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Nescafé Classic 100% Pure Instant Coffee',
    brand: 'Nescafé',
    category: 'Snacks & Beverages',
    subCategory: 'Tea & Coffee',
    description: 'Made from quality Robusta coffee beans, expertly roasted and granulated to give an energizing bold aroma and deep flavor.',
    quantity: '100 g Glass Jar',
    images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=500&q=80'],
    mrp: 395,
    price: 335,
    discount: 15,
    stock: 75,
    rating: 4.8,
    reviewsCount: 215,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Real Fruit Power Mixed Fruit Juice',
    brand: 'Real',
    category: 'Snacks & Beverages',
    subCategory: 'Juice',
    description: 'Delicious blend of 9 handpicked fruits with zero added preservatives. Rich in natural vitamins and dietary goodness.',
    quantity: '1 L Tetra Pack',
    images: ['https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=500&q=80'],
    mrp: 140,
    price: 115,
    discount: 18,
    stock: 80,
    rating: 4.6,
    reviewsCount: 110,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Thums Up Charged Carbonated Drink',
    brand: 'Thums Up',
    category: 'Snacks & Beverages',
    subCategory: 'Soft Drinks',
    description: 'Taste the Thunder. Bold spicy cola kick with maximum fizz and tingling carbonation.',
    quantity: '750 ml Bottle',
    images: ['https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=500&q=80'],
    mrp: 45,
    price: 39,
    discount: 13,
    stock: 120,
    rating: 4.7,
    reviewsCount: 185,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-20 mins'
  },

  // 5. Household & Cleaning
  {
    name: 'Surf Excel Easy Wash Detergent Powder',
    brand: 'Surf Excel',
    category: 'Household & Cleaning',
    subCategory: 'Detergents',
    description: 'Removes tough dried stains like clay, ink, oil, ketchup with ease without dulling colorful fabrics.',
    quantity: '1 KG',
    images: ['https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80'],
    mrp: 165,
    price: 144,
    discount: 13,
    stock: 110,
    rating: 4.8,
    reviewsCount: 230,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Ariel Matic Front Load Liquid Detergent',
    brand: 'Ariel',
    category: 'Household & Cleaning',
    subCategory: 'Detergents',
    description: 'Tough stain removal in 1 wash inside the machine. Specially formulated for front load fully automatic washers.',
    quantity: '1 L Bottle',
    images: ['https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=500&q=80'],
    mrp: 260,
    price: 219,
    discount: 16,
    stock: 65,
    rating: 4.7,
    reviewsCount: 95,
    isPopular: false,
    isFlashDeal: true,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Vim Dishwash Gel Lemon Anti-Germ',
    brand: 'Vim',
    category: 'Household & Cleaning',
    subCategory: 'Cleaning Products',
    description: 'Powers through burnt grease on kadhais and oily tiffins with just 1 spoon. Leaves zero white residue on utensils.',
    quantity: '750 ml Bottle',
    images: ['https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?auto=format&fit=crop&w=500&q=80'],
    mrp: 185,
    price: 149,
    discount: 19,
    stock: 140,
    rating: 4.8,
    reviewsCount: 210,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Harpic Power Plus Disinfectant Toilet Cleaner',
    brand: 'Harpic',
    category: 'Household & Cleaning',
    subCategory: 'Cleaning Products',
    description: '10x better stain and limescale removal. Thick blue liquid coats bowl uniformly and eliminates 99.9% germs.',
    quantity: '1 L Bottle',
    images: ['https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=500&q=80'],
    mrp: 225,
    price: 189,
    discount: 16,
    stock: 110,
    rating: 4.8,
    reviewsCount: 190,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Lizol Floral Disinfectant Surface Cleaner',
    brand: 'Lizol',
    category: 'Household & Cleaning',
    subCategory: 'Cleaning Products',
    description: '10x germ kill formula recommended by Indian Medical Association. Cleans tiles, marble and counters leaving floral freshness.',
    quantity: '1 L Bottle',
    images: ['https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?auto=format&fit=crop&w=500&q=80'],
    mrp: 230,
    price: 195,
    discount: 15,
    stock: 95,
    rating: 4.7,
    reviewsCount: 160,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Scotch-Brite Heavy Duty Scrub Pad',
    brand: 'Scotch-Brite',
    category: 'Household & Cleaning',
    subCategory: 'Kitchen Essentials',
    description: 'High-density mineral coated green scrub pad. Cuts grease quickly and lasts 3x longer than ordinary pads.',
    quantity: 'Pack of 3',
    images: ['https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80'],
    mrp: 75,
    price: 59,
    discount: 21,
    stock: 120,
    rating: 4.8,
    reviewsCount: 130,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Origami Soft 2-Ply Kitchen Towel Rolls',
    brand: 'Origami',
    category: 'Household & Cleaning',
    subCategory: 'Paper Products',
    description: 'Extra absorbent, food-safe paper towels with embossed pockets. Mops spills and drains excess oil from fried snacks.',
    quantity: '2 Rolls Pack',
    images: ['https://images.unsplash.com/photo-1584556812952-905ffd0c611a?auto=format&fit=crop&w=500&q=80'],
    mrp: 150,
    price: 119,
    discount: 21,
    stock: 75,
    rating: 4.6,
    reviewsCount: 80,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },

  // 6. Personal Care
  {
    name: 'Dettol Original Germ Protection Bathing Soap',
    brand: 'Dettol',
    category: 'Personal Care',
    subCategory: 'Soaps & Body Wash',
    description: 'Trusted antibacterial soap bar enriched with moisturizers. Keeps skin healthy and protected from 100 illness-causing germs.',
    quantity: 'Pack of 4 (125 g each)',
    images: ['https://images.unsplash.com/photo-1607006314177-3e8139535e69?auto=format&fit=crop&w=500&q=80'],
    mrp: 230,
    price: 195,
    discount: 15,
    stock: 130,
    rating: 4.8,
    reviewsCount: 240,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Dove Cream Beauty Bathing Bar',
    brand: 'Dove',
    category: 'Personal Care',
    subCategory: 'Soaps & Body Wash',
    description: 'Formulated with 1/4th moisturizing cream and gentle cleansers. Does not dry skin like ordinary soaps.',
    quantity: 'Pack of 3 (100 g each)',
    images: ['https://images.unsplash.com/photo-1607006314177-3e8139535e69?auto=format&fit=crop&w=500&q=80'],
    mrp: 210,
    price: 179,
    discount: 15,
    stock: 90,
    rating: 4.7,
    reviewsCount: 150,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Head & Shoulders Cool Menthol Anti-Dandruff Shampoo',
    brand: 'Head & Shoulders',
    category: 'Personal Care',
    subCategory: 'Hair Care',
    description: 'Menthol fresh blast with zinc pyrithione formula. Fights dandruff flakes and calms itchy scalp.',
    quantity: '340 ml Bottle',
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=500&q=80'],
    mrp: 375,
    price: 310,
    discount: 17,
    stock: 80,
    rating: 4.7,
    reviewsCount: 165,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Colgate Total 12H Antibacterial Toothpaste',
    brand: 'Colgate',
    category: 'Personal Care',
    subCategory: 'Oral Care',
    description: 'Fights plaque, prevents cavities, strengthens enamel and refreshes breath for whole mouth health.',
    quantity: '150 g x 2 Saver Pack',
    images: ['https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=500&q=80'],
    mrp: 260,
    price: 215,
    discount: 17,
    stock: 105,
    rating: 4.8,
    reviewsCount: 195,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Nivea Soft Light Moisturizing Cream',
    brand: 'Nivea',
    category: 'Personal Care',
    subCategory: 'Skin Care',
    description: 'Light texture with Vitamin E and Jojoba Oil. Absorbs instantly into skin providing non-sticky soft touch.',
    quantity: '200 ml Tub',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=500&q=80'],
    mrp: 340,
    price: 279,
    discount: 18,
    stock: 70,
    rating: 4.8,
    reviewsCount: 140,
    isPopular: false,
    isFlashDeal: true,
    deliveryEstimate: '15-25 mins'
  },

  // 7. Baby Care
  {
    name: 'Pampers All-Round Protection Diaper Pants (Medium)',
    brand: 'Pampers',
    category: 'Baby Care',
    subCategory: 'Diapers & Wipes',
    description: 'Magic gel core with up to 12 hours absorption and anti-rash lotion with Aloe Vera. Ultra-soft breathable waistband.',
    quantity: '54 Pants (Size M: 7-12 kg)',
    images: ['https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=500&q=80'],
    mrp: 899,
    price: 749,
    discount: 17,
    stock: 60,
    rating: 4.8,
    reviewsCount: 220,
    isPopular: true,
    isFlashDeal: true,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Himalaya Gentle Baby Wipes with Aloe & Lotus',
    brand: 'Himalaya',
    category: 'Baby Care',
    subCategory: 'Diapers & Wipes',
    description: 'Hypoallergenic, alcohol-free and soap-free soft wipes. Soothes delicate infant skin during diaper changes.',
    quantity: 'Pack of 72 Wipes',
    images: ['https://images.unsplash.com/photo-1584556812952-905ffd0c611a?auto=format&fit=crop&w=500&q=80'],
    mrp: 190,
    price: 149,
    discount: 22,
    stock: 85,
    rating: 4.7,
    reviewsCount: 130,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Nestlé Cerelac Baby Cereal (Wheat-Apple)',
    brand: 'Nestlé',
    category: 'Baby Care',
    subCategory: 'Baby Food',
    description: 'Stage 1 complementary food for babies 6 months and older. Fortified with Iron, Vitamin C and Bifidus BL probiotics.',
    quantity: '300 g Bib Bag',
    images: ['https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80'],
    mrp: 295,
    price: 275,
    discount: 7,
    stock: 50,
    rating: 4.8,
    reviewsCount: 95,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '20-30 mins'
  },
  {
    name: 'Johnson\'s No More Tears Baby Shampoo',
    brand: 'Johnson\'s',
    category: 'Baby Care',
    subCategory: 'Baby Hygiene',
    description: 'Mild as pure water to the eyes. Gently lathers and rinses easily leaving infant hair silky soft and clean.',
    quantity: '200 ml Bottle',
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=500&q=80'],
    mrp: 215,
    price: 185,
    discount: 14,
    stock: 65,
    rating: 4.8,
    reviewsCount: 110,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },

  // 8. Stationery & Essentials
  {
    name: 'Classmate Pulse Long Spiral Notebook',
    brand: 'Classmate',
    category: 'Stationery & Essentials',
    subCategory: 'Notebooks & Pens',
    description: '300 pages unruled single line spiral bound notebook with chlorine-free bright ozone paper.',
    quantity: 'Pack of 2',
    images: ['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=500&q=80'],
    mrp: 220,
    price: 185,
    discount: 16,
    stock: 90,
    rating: 4.7,
    reviewsCount: 85,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Cello Butterflow Classic Blue Ball Pens',
    brand: 'Cello',
    category: 'Stationery & Essentials',
    subCategory: 'Notebooks & Pens',
    description: 'Ultra-low viscosity ink for smudge-free, buttery smooth cursive writing. Ergonomic soft rubber grip.',
    quantity: 'Pack of 5',
    images: ['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=500&q=80'],
    mrp: 50,
    price: 45,
    discount: 10,
    stock: 120,
    rating: 4.8,
    reviewsCount: 140,
    isPopular: false,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'Duracell Chhota Power Alkaline AA Batteries',
    brand: 'Duracell',
    category: 'Stationery & Essentials',
    subCategory: 'Batteries & Home Utilities',
    description: 'Long-lasting alkaline power for TV remotes, wall clocks, wireless mice and electronic toys.',
    quantity: 'Pack of 4',
    images: ['https://images.unsplash.com/photo-1619725002198-6a689b72f41d?auto=format&fit=crop&w=500&q=80'],
    mrp: 160,
    price: 135,
    discount: 16,
    stock: 100,
    rating: 4.8,
    reviewsCount: 160,
    isPopular: true,
    isFlashDeal: false,
    deliveryEstimate: '15-25 mins'
  },
  {
    name: 'All Out Ultra Mosquito Vaporizer Refill',
    brand: 'All Out',
    category: 'Stationery & Essentials',
    subCategory: 'Batteries & Home Utilities',
    description: 'Power+ thermal repellent formula provides uninterrupted sleep protection against dengue and malaria mosquitoes.',
    quantity: 'Twin Pack (45 ml x 2)',
    images: ['https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?auto=format&fit=crop&w=500&q=80'],
    mrp: 175,
    price: 149,
    discount: 15,
    stock: 80,
    rating: 4.6,
    reviewsCount: 75,
    isPopular: false,
    isFlashDeal: true,
    deliveryEstimate: '15-25 mins'
  }
];

// Generate complementary products programmatically up to 105 total products
const brandsList = [
  'Tata', 'Amul', 'Nestlé', 'Britannia', 'Patanjali', 'Dabur', 'Haldiram\'s',
  'MTR', 'Everest', 'Godrej', 'Dettol', 'Surf Excel', 'Colgate', 'Himalaya'
];

const subcategoriesPool = [
  { cat: 'Grocery & Staples', sub: 'Spices', name: 'Kashmiri Saffron Strand Box', qty: '1 g', mrp: 450, price: 390 },
  { cat: 'Grocery & Staples', sub: 'Oil & Ghee', name: 'Patanjali Pure Mustard Oil', qty: '1 L Pouch', mrp: 160, price: 138 },
  { cat: 'Grocery & Staples', sub: 'Dal & Pulses', name: 'Organic Masoor Malka Dal', qty: '1 KG', mrp: 145, price: 119 },
  { cat: 'Grocery & Staples', sub: 'Rice', name: 'Fortune Everyday Basmati Rice', qty: '5 KG', mrp: 380, price: 320 },
  { cat: 'Grocery & Staples', sub: 'Spices', name: 'Catch Black Pepper Sprinkler', qty: '100 g', mrp: 130, price: 110 },
  { cat: 'Fresh Produce', sub: 'Vegetables', name: 'Fresh Green Capsicum (Shimla Mirch)', qty: '500 g', mrp: 45, price: 34 },
  { cat: 'Fresh Produce', sub: 'Vegetables', name: 'Fresh Cauliflower (Gobhi)', qty: '1 Pc (~600 g)', mrp: 40, price: 29 },
  { cat: 'Fresh Produce', sub: 'Vegetables', name: 'Farm Fresh Carrots (Gajar)', qty: '500 g', mrp: 35, price: 26 },
  { cat: 'Fresh Produce', sub: 'Vegetables', name: 'Fresh Cucumbers (Kakdi)', qty: '500 g', mrp: 30, price: 22 },
  { cat: 'Fresh Produce', sub: 'Vegetables', name: 'Fresh Bottle Gourd (Lauki)', qty: '1 Pc (~500 g)', mrp: 35, price: 25 },
  { cat: 'Fresh Produce', sub: 'Vegetables', name: 'Fresh Green Peas (Matar)', qty: '500 g', mrp: 60, price: 45 },
  { cat: 'Fresh Produce', sub: 'Fruits', name: 'Sweet Papaya (Papita)', qty: '1 Pc (~900 g)', mrp: 65, price: 48 },
  { cat: 'Fresh Produce', sub: 'Fruits', name: 'Thompson Seedless Green Grapes', qty: '500 g Box', mrp: 90, price: 69 },
  { cat: 'Fresh Produce', sub: 'Fruits', name: 'Fresh Sweet Watermelon', qty: '1 Pc (~2.5 kg)', mrp: 80, price: 59 },
  { cat: 'Fresh Produce', sub: 'Fruits', name: 'Kinnow Mandarin Citrus', qty: '1 KG', mrp: 95, price: 75 },
  { cat: 'Fresh Produce', sub: 'Fruits', name: 'Green Guava (Amrood)', qty: '500 g', mrp: 50, price: 38 },
  { cat: 'Dairy & Eggs', sub: 'Milk', name: 'Mother Dairy Cow Milk Pouch', qty: '500 ml', mrp: 29, price: 29 },
  { cat: 'Dairy & Eggs', sub: 'Curd & Paneer', name: 'Gowardhan Fresh Paneer', qty: '200 g', mrp: 92, price: 82 },
  { cat: 'Dairy & Eggs', sub: 'Butter & Cheese', name: 'Amul Cheese Block', qty: '200 g', mrp: 135, price: 124 },
  { cat: 'Dairy & Eggs', sub: 'Butter & Cheese', name: 'Amul Salted Butter Tub', qty: '500 g', mrp: 275, price: 260 },
  { cat: 'Dairy & Eggs', sub: 'Curd & Paneer', name: 'Mother Dairy Classic Dahi Tub', qty: '400 g', mrp: 40, price: 38 },
  { cat: 'Dairy & Eggs', sub: 'Milk', name: 'Amul Kool Kesar Badam Drink', qty: '200 ml Bottle', mrp: 35, price: 32 },
  { cat: 'Dairy & Eggs', sub: 'Eggs', name: 'Chabaa Cage-Free White Eggs', qty: 'Pack of 12', mrp: 120, price: 98 },
  { cat: 'Dairy & Eggs', sub: 'Curd & Paneer', name: 'Epigamia Greek Yogurt (Blueberry)', qty: '90 g Cup', mrp: 55, price: 48 },
  { cat: 'Snacks & Beverages', sub: 'Biscuits', name: 'Oreo Original Vanilla Creme Sandwich', qty: '120 g', mrp: 40, price: 35 },
  { cat: 'Snacks & Beverages', sub: 'Biscuits', name: 'Monaco Salted Crackers', qty: '200 g', mrp: 45, price: 39 },
  { cat: 'Snacks & Beverages', sub: 'Biscuits', name: 'Bourbon Chocolate Cream Biscuits', qty: '150 g', mrp: 40, price: 34 },
  { cat: 'Snacks & Beverages', sub: 'Chips & Namkeen', name: 'Bingo Tedhe Medhe Masala Tadka', qty: '90 g', mrp: 30, price: 25 },
  { cat: 'Snacks & Beverages', sub: 'Chips & Namkeen', name: 'Haldiram\'s Moong Dal Namkeen', qty: '200 g', mrp: 60, price: 52 },
  { cat: 'Snacks & Beverages', sub: 'Chips & Namkeen', name: 'Balaji Wafers Simply Salted', qty: '130 g', mrp: 40, price: 35 },
  { cat: 'Snacks & Beverages', sub: 'Chocolates', name: 'Nestlé KitKat 4 Finger Chocolate', qty: '38.5 g', mrp: 35, price: 30 },
  { cat: 'Snacks & Beverages', sub: 'Chocolates', name: 'Ferrero Rocher Hazelnut Pralines', qty: 'Pack of 4', mrp: 175, price: 155 },
  { cat: 'Snacks & Beverages', sub: 'Chocolates', name: 'Cadbury 5 Star Chocolate Bar', qty: '40 g', mrp: 20, price: 18 },
  { cat: 'Snacks & Beverages', sub: 'Soft Drinks', name: 'Coca-Cola Zero Sugar Can', qty: '300 ml', mrp: 40, price: 36 },
  { cat: 'Snacks & Beverages', sub: 'Soft Drinks', name: 'Sprite Clear Lemon-Lime Cold Drink', qty: '750 ml', mrp: 45, price: 39 },
  { cat: 'Snacks & Beverages', sub: 'Tea & Coffee', name: 'Brooke Bond Red Label Tea', qty: '500 g', mrp: 290, price: 249 },
  { cat: 'Snacks & Beverages', sub: 'Tea & Coffee', name: 'Wagh Bakri Premium Leaf Tea', qty: '500 g', mrp: 310, price: 265 },
  { cat: 'Snacks & Beverages', sub: 'Tea & Coffee', name: 'Bru Instant Coffee Jar', qty: '100 g', mrp: 235, price: 199 },
  { cat: 'Snacks & Beverages', sub: 'Juice', name: 'Tropicana 100% Orange Juice', qty: '1 L', mrp: 150, price: 125 },
  { cat: 'Snacks & Beverages', sub: 'Juice', name: 'Paper Boat Aamras Mango Juice', qty: '200 ml', mrp: 35, price: 30 },
  { cat: 'Household & Cleaning', sub: 'Detergents', name: 'Tide Plus Extra Power Detergent Powder', qty: '1 KG', mrp: 140, price: 119 },
  { cat: 'Household & Cleaning', sub: 'Detergents', name: 'Rin Detergent Bar Pack of 4', qty: '250 g x 4', mrp: 90, price: 78 },
  { cat: 'Household & Cleaning', sub: 'Cleaning Products', name: 'Colin Glass and Household Cleaner Spray', qty: '500 ml', mrp: 115, price: 95 },
  { cat: 'Household & Cleaning', sub: 'Cleaning Products', name: 'Pril Lime Degreasing Dishwash Liquid', qty: '750 ml', mrp: 180, price: 149 },
  { cat: 'Household & Cleaning', sub: 'Kitchen Essentials', name: 'Hindalco Freshwrap Aluminium Foil 11m', qty: '1 Roll', mrp: 110, price: 89 },
  { cat: 'Household & Cleaning', sub: 'Kitchen Essentials', name: 'Shalimar Oxo-Biodegradable Garbage Bags', qty: '30 Bags (Medium)', mrp: 120, price: 95 },
  { cat: 'Household & Cleaning', sub: 'Paper Products', name: 'Origami Facial Tissues Box', qty: '100 Pulls', mrp: 95, price: 79 },
  { cat: 'Personal Care', sub: 'Hair Care', name: 'Parachute 100% Pure Coconut Hair Oil', qty: '500 ml Bottle', mrp: 215, price: 185 },
  { cat: 'Personal Care', sub: 'Hair Care', name: 'Dove Daily Shine Shampoo', qty: '340 ml', mrp: 340, price: 285 },
  { cat: 'Personal Care', sub: 'Hair Care', name: 'Tresemme Keratin Smooth Conditioner', qty: '190 ml', mrp: 260, price: 215 },
  { cat: 'Personal Care', sub: 'Oral Care', name: 'Sensodyne Fresh Mint Sensitivity Toothpaste', qty: '75 g', mrp: 160, price: 139 },
  { cat: 'Personal Care', sub: 'Oral Care', name: 'Oral-B CrossAction Soft Toothbrush', qty: 'Pack of 3', mrp: 140, price: 115 },
  { cat: 'Personal Care', sub: 'Oral Care', name: 'Close-Up Red Hot Gel Toothpaste', qty: '150 g', mrp: 120, price: 99 },
  { cat: 'Personal Care', sub: 'Skin Care', name: 'Vaseline Intensive Care Deep Moisture Body Lotion', qty: '400 ml', mrp: 399, price: 319 },
  { cat: 'Baby Care', sub: 'Diapers & Wipes', name: 'MamyPoko Pants Extra Absorb (Large)', qty: '48 Diaper Pants', mrp: 849, price: 699 },
  { cat: 'Baby Care', sub: 'Diapers & Wipes', name: 'Huggies Wonder Pants Diapers (Small)', qty: '42 Pants', mrp: 699, price: 569 },
  { cat: 'Baby Care', sub: 'Baby Hygiene', name: 'Sebamed Baby Gentle Wash Ultra Mild', qty: '200 ml', mrp: 440, price: 385 },
  { cat: 'Baby Care', sub: 'Baby Hygiene', name: 'Johnson\'s Baby Powder with Natural Cornstarch', qty: '200 g', mrp: 165, price: 139 },
  { cat: 'Stationery & Essentials', sub: 'Notebooks & Pens', name: 'Nataraj 621 Bold Pencils Box', qty: 'Pack of 10 + Sharpener', mrp: 60, price: 50 },
  { cat: 'Stationery & Essentials', sub: 'Adhesives', name: 'Fevicol MR Squeeze Bottle', qty: '100 g', mrp: 40, price: 35 },
  { cat: 'Stationery & Essentials', sub: 'Batteries & Home Utilities', name: 'Eveready AAA Alkaline Batteries', qty: 'Pack of 4', mrp: 140, price: 119 },
  { cat: 'Stationery & Essentials', sub: 'Batteries & Home Utilities', name: 'GoodKnight Gold Flash Mosquito Refill', qty: '45 ml', mrp: 90, price: 79 }
];

subcategoriesPool.forEach((item, index) => {
  const brand = brandsList[index % brandsList.length];
  const discount = Math.round(((item.mrp - item.price) / item.mrp) * 100);
  products.push({
    name: `${brand} ${item.name}`,
    brand,
    category: item.cat,
    subCategory: item.sub,
    description: `Authentic ${item.name} provided by ${brand}. Fresh, sealed and certified quality guaranteed under MART WITH US standards.`,
    quantity: item.qty,
    images: [`https://images.unsplash.com/photo-${1580000000000 + (index * 4123) % 90000000000}?auto=format&fit=crop&w=500&q=80`],
    mrp: item.mrp,
    price: item.price,
    discount,
    stock: 40 + (index * 3) % 90,
    rating: Number((4.3 + ((index % 6) * 0.1)).toFixed(1)),
    reviewsCount: 25 + (index * 5) % 150,
    isPopular: index % 3 === 0,
    isFlashDeal: index % 4 === 0,
    deliveryEstimate: '15-25 mins'
  });
});

module.exports = {
  categories,
  stores,
  products
};
